print("Baby shark")
print(" doo"*4)
print(22.5 + 398)
print(990/5.65)
print(93.6-5.72*89)
#type function
print(type(9))
print(type(4.7))
print(type("fywytefv"))
print(type(56656>=1234567))
print(type(523745>=3987654))
#text-symbols.com/ascii_art
print(int("34")+54+2.5)
print("34"+str(2.5)+str(54))
# isupper()
# islower()
# isalpha()
# isdigit()
# isalnum()
# istitle()
# startswith()
# endswith()
print("SID".isupper())
print("sid".islower())
print("sid".isalpha())
print("sid".isdigit())
print("sid".isalnum())
print("sid".istitle())
print("Sid".startswith("s"))
print("sid".endswith("d"))
print("sid".upper())
print("SID".lower())
print("sid".capitalize())
print("sid".replace("sid","qqwertytfghytrdfghgfdsedrfghj"))
print("sid".swapcase())
print("siddharth sachan".count("a"))
print("suJJu".title())
